version: '3'

services:
  server:
    image: calitb/python_server
    build:
      context: ./python
    container_name: python_server
    ports:
      - 90:8080
    volumes:
      - ./python/src:/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql
  mysql:
    image: calitb/mysql_python
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    container_name: mysql_python
    ports:
      - 3308:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8083:8080
    environment:
      ADMINER_DESIGN: price
    depends_on:
      - mysql
